### PR TITLE
#165 Skip setters if required

### PR DESCRIPTION
**Pull request by pabloelcolombiano**

### CODE REVIEW

**Comment by pabloelcolombiano** [comment]
@Erwane thanks for the hint. This is now implemented. Let me know if this looks good enough for you.

**Comment by Erwane** [comment]
It's looks okay.
I don't like mutable array (`&$data`) but it's working ;)

Thanks

**Comment by pabloelcolombiano** [comment]
Good catch, this was a rest of an early implementation. Fixed, merging this.

**Comment by Erwane** [comment]
Thanks :+1:

**Pull request merged**
